### ISSUE TITLE
Error when trying to login in microsoft

### ISSUE THREAD

**Issue by devCore1** [Fentanyl-Client/Microsoft-Login#1]
Thanks for your effort in making this login process simple.

I'm getting following error, when logging into my account after the opened microsoft popup.
`Exception in thread "pool-4-thread-1" java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
	at tech.fentanyl.microsoftlogin.impl.login.web.WebLogic.authXSTS(WebLogic.java:145)
	at tech.fentanyl.microsoftlogin.impl.login.web.WebLogic.auth(WebLogic.java:49)
	at tech.fentanyl.microsoftlogin.impl.login.web.WebHandler.handle(WebHandler.java:25)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

I've added your jar file with dependencies to my libraries and i've implemented it like that in my code:

![grafik](https://github.com/Fentanyl-Client/Microsoft-Login/assets/62718936/a1d1ae3d-05ca-4a65-8b54-83c2dfba4395)

Did i miss something?

**Comment by devCore1** [comment]
That solved it, thanks a lot!
